#!/bin/bash
# Grab Tourney Stats — drives OOTP's Examine → Statistics → Sortable Stats →
# Report → Write to CSV loop, and files each export under its real event id.
#
# WHY THIS EXISTS: the run number used to be typed by hand and was often wrong
# (Bronze OOTP Era's files are named 147/150/161; the real id says 153). Here the
# id comes off the Your Tournaments screen, so the filename cannot be wrong.
#
# BEFORE RUNNING
#   • OOTP full screen on the SAMSUNG, "Your Tournaments", your usual filters
#   • the list scrolled to the top
#   • Terminal has Accessibility (System Settings → Privacy & Security → Accessibility)
#   • do not touch the mouse while it runs
#
# The WORKLIST below is generated by Claude from the live screen: one line per
# tournament, "<row number> <output filename>". Row 1 is the first row under the
# header. Only completed events are ever listed.

set -uo pipefail
CLICLICK=/opt/homebrew/bin/cliclick
LAND="$HOME/Application Support/Out of the Park Developments/OOTP Baseball 27/online_data/statistics_player_statistics_-_sortable_stats_cwhit_view.csv"
DEST="$HOME/Desktop/OOTP Perfect Team/Archive/Completed"

# --- verified screen positions (SAMSUNG at global origin 1920,0) -------------
EXAMINE_X=3713           # the Examine column
ROW1_Y=248               # centre of row 1
ROW_PITCH=26             # rows are evenly spaced
TOURNAMENT_CHEV="2662,25"   # the CHEVRON, not the word — the label does not open it
MENU_STATISTICS="2486,186"
TAB_SORTABLE="2843,247"
REPORT_CHEV="3040,327"
WRITE_CSV="3029,384"
BACK_ARROW="1962,25"

WAIT_OPEN=9              # Examine → tournament loaded
WAIT_PAGE=4              # page/tab transitions
WAIT_EXPORT=5            # Write to CSV → file on disk

# --- WORKLIST: <row> <filename> ---------------------------------------------
WORKLIST=$(cat <<'LIST'
LIST
)

[ -x "$CLICLICK" ] || { echo "cliclick missing — brew install cliclick"; exit 1; }
mkdir -p "$DEST"
click() { "$CLICLICK" m:"$1" w:300 c:"$1"; }

ok=0; skipped=0; failed=0
while read -r row out; do
  [ -z "${row:-}" ] && continue
  case "$row" in \#*) continue;; esac

  if [ -e "$DEST/$out" ]; then
    echo "· $out — already have it, skipping"; skipped=$((skipped+1)); continue
  fi

  # remember the landing file so we can prove a NEW export actually happened.
  # without this a missed click would file the PREVIOUS tournament under this name.
  before=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")

  y=$(( ROW1_Y + (row - 1) * ROW_PITCH ))
  echo "→ row $row → $out"
  click "$EXAMINE_X,$y";      sleep "$WAIT_OPEN"
  click "$TOURNAMENT_CHEV";   sleep 1
  click "$MENU_STATISTICS";   sleep "$WAIT_PAGE"
  click "$TAB_SORTABLE";      sleep "$WAIT_PAGE"
  click "$REPORT_CHEV";       sleep 1
  click "$WRITE_CSV";         sleep "$WAIT_EXPORT"

  after=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")
  if [ "$after" = "$before" ] || [ "$after" = "none" ]; then
    echo "  ✗ no new export appeared — a click missed. Stopping so nothing is filed wrong."
    echo "    Put the list back at the top and rerun; everything already filed is kept."
    failed=$((failed+1)); break
  fi

  mv "$LAND" "$DEST/$out"
  echo "  ✓ $(wc -l < "$DEST/$out" | tr -d ' ') lines"
  ok=$((ok+1))

  click "$BACK_ARROW";        sleep "$WAIT_PAGE"
done <<< "$WORKLIST"

echo
echo "filed $ok · skipped $skipped · failed $failed"
[ "$ok" -gt 0 ] && echo "Next: tell Claude, or run  cd web && pnpm import:observed && pnpm fit:projection"
