#!/bin/bash
# Grab Tourney Stats — drives OOTP's Examine → Statistics → Sortable Stats →
# Report → Write to CSV loop, and files each export under its real event id.
#
# WHY THIS EXISTS: the run number used to be typed by hand and was often wrong
# (Bronze OOTP Era's files are named 147/150/161; the real id says 153). Here the
# id comes off the Your Tournaments screen, so the filename cannot be wrong.
#
# BEFORE RUNNING
#   • OOTP full screen on the SAMSUNG, "Your Tournaments", your usual filters
#   • the list scrolled to the top
#   • Auto-Refresh set to None — otherwise the rows re-sort mid-run and the
#     wrong tournament gets filed under the next name
#   • Terminal has Accessibility (System Settings → Privacy & Security → Accessibility)
#   • do not touch the mouse while it runs
#
# The WORKLIST below is generated by Claude from the live screen: one line per
# tournament, "<row> <filename> <field size>". Row 1 is the first row under the
# header. Only completed events with data are ever listed.

set -uo pipefail
CLICLICK=/opt/homebrew/bin/cliclick
LAND="$HOME/Application Support/Out of the Park Developments/OOTP Baseball 27/online_data/statistics_player_statistics_-_sortable_stats_cwhit_view.csv"
DEST="$HOME/Desktop/OOTP Perfect Team/Archive/Completed"
LOG="$HOME/Desktop/OOTP Perfect Team/Archive/grab-log.txt"

# MODE=manual  you click EXAMINE and navigate back; the script does only the six
#              blind export clicks. No return_to_list, so nothing can get lost.
# MODE=auto    the old fully-automatic loop, including the start-screen round trip.
MODE=manual

exec > >(tee -a "$LOG") 2>&1
echo; echo "=== $(date '+%Y-%m-%d %H:%M:%S')  mode=$MODE ==="

# --- verified screen positions (SAMSUNG at global origin 1920,0) -------------
EXAMINE_X=3713              # the Examine column
ROW1_Y=248                  # centre of row 1
ROW_PITCH=26                # rows are evenly spaced
TOURNAMENT_CHEV="2662,25"   # the CHEVRON, not the word — the label does not open it
MENU_STATISTICS="2486,186"
TAB_SORTABLE="2843,247"
REPORT_CHEV="3040,327"      # press-and-HOLD only; a fast click does nothing
WRITE_CSV="3036,385"
DIALOG_OK="3038,615"        # the "COMPLETE — Report Written to…" box
# Getting back to the list. OOTP's "<" back arrow is dead inside Perfect Team,
# and Perfect Team Home only reaches the loaded tournament's overview. The only
# route out is all the way to the OOTP start screen and back in.
MAIN_CHEV="2252,26"
MENU_START_SCREEN="2247,351" # MAIN > OOTP Start Screen
SHOW_PERFECT_DRAFTS="3383,624"
TAB_YOUR_TOURNAMENTS="2426,70"
AUTOREFRESH_CHEV="3692,69"   # coming back through the start screen resets this
AUTOREFRESH_NONE="3627,175"  # to 1 Minute, and then the rows re-sort under us

WAIT_OPEN=18             # Examine → tournament loaded (it is slow; do not trim)
WAIT_PAGE=6              # page/tab transitions
WAIT_EXPORT=7            # Write to CSV → file on disk

# --- WORKLIST: <row> <filename> <teams in the field> ------------------------
# Built 2026-09-04 22:2x Central from a live read of Your Tournaments, list at
# the TOP with no in-flight rows above row 1 (row 1 = Silver Only Cap 1250174,
# Today). 17 of cwhit's 25 missing IDs; the other 8 are below row 31 and need a
# second pass after scrolling. If the top of the list has changed, STOP and ask
# Claude to re-read it — every row index shifts together.
# teams is a sanity check: a 64-team draft cannot produce a 128-team file, so a
# row that has shifted under us is caught before it is filed under a real name.
WORKLIST=$(cat <<'LIST'
2   lowsilveronly_3              64
8   bronzeptcs3_100              64
9   silverandfriends_100         64
12  lowdiamonddaily_173          64
13  bronze10to50_169             64
15  silveronlycap_172            64
16  silverslotsdaily_173         64
17  bronzeptcs3_99               64
19  latesilver_173              128
20  silverandfriends_99          64
22  openslotsdaily_172           64
23  earlygold_172               128
25  silverslotsdaily_172         64
26  diamondandfriends_98         64
27  bronzeootp_155              128
28  bronzeptcs3_98               64
29  earlygold_171               128
LIST
)

[ -x "$CLICLICK" ] || { echo "cliclick missing — brew install cliclick"; exit 1; }
mkdir -p "$DEST"
# OOTP swallows the first click when it is not the frontmost app — and it never
# is, because Terminal has focus the moment you launch this. Raise it first.
# OOTP swallows the first click after it is raised, so spend one on dead space
# in the title bar. Without this the click you cared about silently does nothing
# and every click after it lands on the wrong screen.
focus() {
  osascript -e 'tell application id "com.ootpdevelopments.ootp27macsteam" to activate' >/dev/null 2>&1
  sleep 1
  "$CLICLICK" m:2144,26 w:300 c:2144,26
  sleep 1
}
click() { "$CLICLICK" m:"$1" w:600 c:"$1"; }
# the Report combo ignores a fast click — it only opens on press-and-hold
press() { "$CLICLICK" m:"$1" w:600 dd:"$1" w:300 du:"$1"; }
# a menu item clicked too soon after its menu opens is swallowed — hover longer
slowclick() { "$CLICLICK" m:"$1" w:800 c:"$1"; }

# OOTP queues modal popups — the daily login reward at 00:00 UTC, one "Tournament
# Update"/"Tournament Reward" per event that just ended. Any one of them blocks
# every click until it is dismissed, and Return does not do it. These are the OK
# button positions those boxes use; clicking empty space is absorbed by the modal.
drain_dialogs() {
  focus
  for _ in 1 2 3 4 5 6; do
    for spot in 3046,604 3059,617 3033,591 3070,630 2875,960; do
      "$CLICLICK" m:"$spot" w:150 dd:"$spot" w:150 du:"$spot"
    done
  done
}

# a drafted roster is ~17-24 cards, so each field size lands in its own band
return_to_list() {
  focus
  click "$MAIN_CHEV";            sleep 2
  # the menu must actually be open before the item click, hence the long hovers
  click "$MENU_START_SCREEN";    sleep 12
  click "$SHOW_PERFECT_DRAFTS";  sleep 10
  # the first click on the tab often lands while the screen is still building
  click "$TAB_YOUR_TOURNAMENTS"; sleep 3
  click "$TAB_YOUR_TOURNAMENTS"; sleep "$WAIT_PAGE"
  press "$AUTOREFRESH_CHEV";     sleep 2
  click "$AUTOREFRESH_NONE";     sleep 3
}

band() {
  case "$1" in
     32) echo "500 900";;
     64) echo "1000 1700";;
    128) echo "2000 3400";;
    256) echo "4000 6800";;
      *) echo "1 999999";;
  esac
}

# optional first argument: stop after N tournaments (a smoke test)
LIMIT="${1:-0}"

# --- export_here: run the six blind clicks against whatever tournament is open.
# Returns 0 and leaves the file at $LAND on success.
export_here() {
  focus
  click "$TOURNAMENT_CHEV";   sleep 3
  click "$MENU_STATISTICS";   sleep $((WAIT_PAGE + 2))
  click "$TAB_SORTABLE";      sleep $((WAIT_PAGE + 6))
  press "$REPORT_CHEV";       sleep 4
  slowclick "$WRITE_CSV";     sleep $((WAIT_EXPORT + 2))
}

if [ "$MODE" = "manual" ]; then
  echo "clearing any queued OOTP popups…"
  drain_dialogs
  ok=0; skipped=0; failed=0
  while read -r row out teams; do
    [ -z "${row:-}" ] && continue
    case "$row" in \#*) continue;; esac
    if [ -e "$DEST/$out.csv" ]; then
      echo "· $out — already have it, skipping"; skipped=$((skipped+1)); continue
    fi
    echo
    echo "──────────────────────────────────────────────────────────────"
    echo "  NEXT: $out.csv        (was row $row, ${teams}-team field)"
    echo "  In OOTP: get to Your Tournaments and click EXAMINE on it."
    echo "  Then come back here and press Return.   (s = skip, q = quit)"
    printf "  > "
    read -r reply </dev/tty
    case "$reply" in
      q|Q) echo "  stopping here."; break;;
      s|S) echo "  skipped."; skipped=$((skipped+1)); continue;;
    esac

    before=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")
    export_here
    after=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")
    if [ "$after" = "$before" ] || [ "$after" = "none" ]; then
      echo "  ✗ no file was written — a click missed, or a popup is up."
      drain_dialogs
      echo "    Nothing else was clicked. Re-open the tournament and press Return to retry,"
      echo "    or s to skip."
      printf "  > "; read -r reply2 </dev/tty
      case "$reply2" in s|S) skipped=$((skipped+1)); continue;; esac
      before=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")
      export_here
      after=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")
      if [ "$after" = "$before" ] || [ "$after" = "none" ]; then
        echo "  ✗ still nothing. Giving up on $out."; failed=$((failed+1)); continue
      fi
    fi

    click "$DIALOG_OK"; sleep 2
    lines=$(wc -l < "$LAND" | tr -d ' ')
    read -r lo hi <<< "$(band "$teams")"
    if [ "$lines" -lt "$lo" ] || [ "$lines" -gt "$hi" ]; then
      echo "  ✗ $lines lines is wrong for a ${teams}-team field — that was a different"
      echo "    tournament. NOT filed; $LAND left in place for Claude to look at."
      failed=$((failed+1)); continue
    fi
    mv "$LAND" "$DEST/$out.csv"
    echo "  ✓ filed $out.csv — $lines lines"
    ok=$((ok+1))
  done <<< "$WORKLIST"
  echo
  echo "filed $ok · skipped $skipped · failed $failed"
  echo "Log: $LOG"
  exit 0
fi

echo "clearing any queued OOTP popups…"
drain_dialogs

ok=0; skipped=0; failed=0
while read -r row out teams; do
  if [ "$LIMIT" -gt 0 ] && [ "$ok" -ge "$LIMIT" ]; then break; fi
  [ -z "${row:-}" ] && continue
  case "$row" in \#*) continue;; esac

  if [ -e "$DEST/$out.csv" ]; then
    echo "· $out — already have it, skipping"; skipped=$((skipped+1)); continue
  fi

  y=$(( ROW1_Y + (row - 1) * ROW_PITCH ))
  echo "→ row $row → $out.csv"

  # OOTP's timings wander — a page occasionally takes longer than the sleep and
  # one click lands on nothing. That used to end the run; now the row is simply
  # tried again from the list, which is what a person would do.
  got=""
  for attempt in 1 2 3; do
    [ "$attempt" -gt 1 ] && echo "  … retry $attempt"

    # remember the landing file so we can prove a NEW export actually happened.
    # without this a missed click would file the PREVIOUS tournament under this name.
    before=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")

    focus
    click "$EXAMINE_X,$y";      sleep "$WAIT_OPEN"
    click "$TOURNAMENT_CHEV";   sleep 3
    click "$MENU_STATISTICS";   sleep $((WAIT_PAGE + 2))
    click "$TAB_SORTABLE";      sleep $((WAIT_PAGE + 6))
    press "$REPORT_CHEV";       sleep 4
    slowclick "$WRITE_CSV";     sleep $((WAIT_EXPORT + 2))

    # Only now do we know whether we were ever on the right page. If no file was
    # written we are somewhere unexpected, and clicking on blindly lands on
    # whatever happens to be there — which is how a settings checkbox gets
    # toggled. So check first, and on failure touch nothing but the top bar.
    after=$(stat -f '%m %z' "$LAND" 2>/dev/null || echo "none")
    if [ "$after" = "$before" ] || [ "$after" = "none" ]; then
      echo "  · a click missed; nothing filed, nothing else clicked"
      # almost always a popup that appeared mid-run: OOTP throws a modal every
      # time one of your tournaments starts or ends, and it blocks every click
      drain_dialogs
      return_to_list
      continue
    fi

    click "$DIALOG_OK";         sleep 2   # dismiss "COMPLETE"; it blocks every later click

    lines=$(wc -l < "$LAND" | tr -d ' ')
    read -r lo hi <<< "$(band "$teams")"
    if [ "$lines" -lt "$lo" ] || [ "$lines" -gt "$hi" ]; then
      echo "  ✗ $lines lines is wrong for a $teams-team field — the row order moved."
      echo "    Stopping: the list is not what the worklist was built from."
      rm -f "$LAND"
      return_to_list
      failed=$((failed+1))
      break 2
    fi

    mv "$LAND" "$DEST/$out.csv"
    echo "  ✓ $lines lines"
    ok=$((ok+1)); got=1
    return_to_list
    break
  done

  if [ -z "$got" ]; then
    echo "  ✗ gave up on $out after 3 tries"
    failed=$((failed+1))
  fi
done <<< "$WORKLIST"

echo
echo "filed $ok · skipped $skipped · failed $failed"
[ "$ok" -gt 0 ] && echo "Next: tell Claude, or run  cd web && pnpm import:observed && pnpm fit:projection"
